I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 248, in script
    jump m1_correct_2
ScriptError: could not find label 'm1_correct_2'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 248, in script
    jump m1_correct_2
  File "C:\Users\camer\OneDrive\Desktop\code\renpy-8.3.3-sdk\renpy\ast.py", line 1699, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\camer\OneDrive\Desktop\code\renpy-8.3.3-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'm1_correct_2'.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.3.24111502
theWaterlooGames 1.0
Mon Nov 25 10:03:00 2024
