I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 466, in script
    hide aucoin zino fight with flash
  File "game/script.rpy", line 466, in <module>
    hide aucoin zino fight with flash
NameError: name 'flash' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 466, in script
    hide aucoin zino fight with flash
  File "C:\Users\msmad\Downloads\Waterloo Games - Renpy\renpy-8.3.3-sdk\renpy\ast.py", line 1357, in execute
    paired = renpy.python.py_eval(self.paired)
  File "C:\Users\msmad\Downloads\Waterloo Games - Renpy\renpy-8.3.3-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\msmad\Downloads\Waterloo Games - Renpy\renpy-8.3.3-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 466, in <module>
    hide aucoin zino fight with flash
NameError: name 'flash' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.3.24111502
theWaterlooGames 1.0
Sat Nov 23 00:12:58 2024
